const icons = {
  'arrow-back': 'arrow-back',
  'arrow-forward': 'arrow-forward',
  'calendar-month': 'calendar-month',
  cancel: 'cancel',
  'check-circle': 'check-circle',
  check: 'check',
  close: 'close',
  delete: 'delete',
  'delivery-truck-speed': 'delivery-truck-speed',
  facebook: 'facebook',
  favorite: 'favorite',
  'favorite-filled': 'favorite-filled',
  'featured-seasonal-and-gifts': 'featured-seasonal-and-gifts',
  github: 'github',
  instagram: 'instagram',
  'keyboard-arrow-left': 'keyboard-arrow-left',
  'keyboard-arrow-right': 'keyboard-arrow-right',
  mail: 'mail',
  person: 'person',
  pinterest: 'pinterest',
  'rs-school': 'rs-school',
  search: 'search',
  'search-off': 'search-off',
  'sentiment-excited': 'sentiment-excited',
  'shopping-cart': 'shopping-cart',
  store: 'store',
  twitter: 'twitter',
  'verified-user': 'verified-user',
  'visibility-off': 'visibility-off',
  visibility: 'visibility',
} as const;

export { icons };
